'use strict';
const $=id=>document.getElementById(id);
const el={canvas:$('gameCanvas'),soundButton:$('soundButton'),helpButton:$('helpButton'),themeButton:$('themeButton'),helpDialog:$('helpDialog'),closeHelpButton:$('closeHelpButton'),modeSelect:$('modeSelect'),difficultySelect:$('difficultySelect'),starsValue:$('starsValue'),starsTotal:$('starsTotal'),scoreValue:$('scoreValue'),comboValue:$('comboValue'),timeValue:$('timeValue'),livesValue:$('livesValue'),levelValue:$('levelValue'),bestValue:$('bestValue'),statusBadge:$('statusBadge'),objectiveText:$('objectiveText'),pauseButton:$('pauseButton'),restartButton:$('restartButton'),progressText:$('progressText'),progressTrack:$('progressTrack'),progressBar:$('progressBar'),pauseOverlay:$('pauseOverlay'),resumeButton:$('resumeButton'),resultOverlay:$('resultOverlay'),resultIcon:$('resultIcon'),resultTitle:$('resultTitle'),resultText:$('resultText'),resultScore:$('resultScore'),resultStars:$('resultStars'),resultMoves:$('resultMoves'),nextLevelButton:$('nextLevelButton'),playAgainButton:$('playAgainButton'),messageBox:$('messageBox'),energyValue:$('energyValue'),energyTrack:$('energyTrack'),energyBar:$('energyBar'),coinValue:$('coinValue'),keyValue:$('keyValue'),shieldValue:$('shieldValue'),missionStars:$('missionStars'),missionStarsText:$('missionStarsText'),missionKey:$('missionKey'),missionKeyText:$('missionKeyText'),missionPortal:$('missionPortal'),missionPortalText:$('missionPortalText'),undoTool:$('undoTool'),hintTool:$('hintTool')};
const ctx=el.canvas.getContext('2d');
const toolButtons=[...document.querySelectorAll('.tool-button[data-tool]')];
const CFG={easy:{size:11,time:150,lives:4,stars:5,traps:.025},normal:{size:15,time:110,lives:3,stars:7,traps:.05},hard:{size:19,time:85,lives:2,stars:9,traps:.08}};
const state={grid:[],player:{x:1,y:1},portal:{x:1,y:1},stars:[],crystals:[],traps:[],energyItems:[],key:null,hasKey:false,starsCollected:0,starsTarget:0,score:0,combo:1,lives:3,level:1,moves:0,energy:100,crystalCount:0,keyCount:0,shieldCount:0,timeLeft:110,running:false,paused:false,finished:false,history:[],hintPath:[],best:Number(localStorage.getItem('starforge.best'))||0,soundOn:localStorage.getItem('starforge.sound')!=='0'};
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function maze(n){const g=Array.from({length:n},()=>Array(n).fill(0)),stack=[{x:1,y:1}],dirs=[[0,-2],[2,0],[0,2],[-2,0]];g[1][1]=1;while(stack.length){const c=stack.at(-1),opts=[];for(const[dX,dY]of dirs){const x=c.x+dX,y=c.y+dY;if(x>0&&y>0&&x<n-1&&y<n-1&&!g[y][x])opts.push({x,y,wx:c.x+dX/2,wy:c.y+dY/2})}if(!opts.length){stack.pop();continue}const p=opts[Math.floor(Math.random()*opts.length)];g[p.wy][p.wx]=g[p.y][p.x]=1;stack.push({x:p.x,y:p.y})}return g}
function cells(){const a=[];state.grid.forEach((r,y)=>r.forEach((v,x)=>{if(v&&!(x===1&&y===1))a.push({x,y})}));return shuffle(a)}
function bfs(from,to,avoidTraps=false){const n=state.grid.length,q=[from],prev=new Map([[from.y*n+from.x,null]]),blocked=new Set(avoidTraps?state.traps.map(t=>t.y*n+t.x):[]),dirs=[[0,-1],[1,0],[0,1],[-1,0]];while(q.length){const c=q.shift(),ck=c.y*n+c.x;if(c.x===to.x&&c.y===to.y){const path=[];let p=c;while(p){path.unshift(p);p=prev.get(p.y*n+p.x)}return path}for(const[dx,dy]of dirs){const x=c.x+dx,y=c.y+dy,k=y*n+x;if(x<0||y<0||x>=n||y>=n||!state.grid[y][x]||prev.has(k)||blocked.has(k))continue;prev.set(k,c);q.push({x,y})}}return[]}
function ensureRoute(){state.traps=state.traps.filter(t=>{const test=state.traps.filter(x=>x!==t),old=state.traps;state.traps=test;const ok=(!state.key||bfs(state.player,state.key,true).length)&&(!state.key||bfs(state.key,state.portal,true).length);state.traps=old;return !ok});}
function build(keep=false){const c=CFG[el.difficultySelect.value],a=(state.grid=maze(c.size),cells());state.player={x:1,y:1};state.portal=a.pop();state.stars=a.splice(0,c.stars+Math.floor((state.level-1)/2));state.crystals=a.splice(0,4);state.energyItems=a.splice(0,3);state.key=a.pop();state.traps=a.splice(0,Math.floor(a.length*c.traps));ensureRoute();state.starsTarget=state.stars.length;state.starsCollected=0;state.hasKey=false;state.moves=0;state.energy=100;state.combo=1;state.history=[];state.hintPath=[];state.finished=false;state.paused=false;state.running=true;state.timeLeft=el.modeSelect.value==='survival'?c.time*2:el.modeSelect.value==='challenge'?Math.round(c.time*.7):c.time;state.lives=el.modeSelect.value==='survival'?1:c.lives;if(!keep){state.score=0;state.level=1;state.crystalCount=state.keyCount=state.shieldCount=0}hide();status('Misiune activă');el.objectiveText.textContent='Colectează toate stelele.';msg('Misiune începută. Găsește prima steluță.');sync();draw()}
function idx(a,x,y){return a.findIndex(p=>p.x===x&&p.y===y)}
function move(dir){if(!state.running||state.paused||state.finished)return;const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir],x=state.player.x+d[0],y=state.player.y+d[1];if(!state.grid[y]?.[x]){msg('Perete. Încearcă altă direcție.');return}state.history.push(JSON.stringify({player:state.player,score:state.score,stars:state.stars,starsCollected:state.starsCollected,crystals:state.crystals,energyItems:state.energyItems,traps:state.traps,lives:state.lives,hasKey:state.hasKey,energy:state.energy,combo:state.combo}));if(state.history.length>40)state.history.shift();state.player={x,y};state.moves++;state.hintPath=[];collect();trap();portal();sync();draw()}
function collect(){let i=idx(state.stars,state.player.x,state.player.y);if(i>=0){state.stars.splice(i,1);state.starsCollected++;state.combo=Math.min(9,state.combo+1);state.score+=100*state.combo;msg(`Stea colectată! Combo x${state.combo}.`)}i=idx(state.crystals,state.player.x,state.player.y);if(i>=0){state.crystals.splice(i,1);state.crystalCount++;state.score+=50;msg('Cristal recuperat. +50 puncte.')}i=idx(state.energyItems,state.player.x,state.player.y);if(i>=0){state.energyItems.splice(i,1);state.energy=Math.min(100,state.energy+30);msg('Energie recuperată. +30%.')}if(state.key&&state.key.x===state.player.x&&state.key.y===state.player.y){state.key=null;state.hasKey=true;state.keyCount++;state.score+=150;msg('Cheie recuperată. Portalul poate fi deblocat.')}}
function trap(){const i=idx(state.traps,state.player.x,state.player.y);if(i<0)return;state.traps.splice(i,1);if(state.shieldCount){state.shieldCount--;msg('Scutul a absorbit capcana.');return}state.lives--;state.combo=1;state.score=Math.max(0,state.score-60);msg('Capcană! Ai pierdut o viață.');if(state.lives<=0)finish(false,'Nucleul a cedat. Misiune eșuată.')}
function portal(){if(state.player.x!==state.portal.x||state.player.y!==state.portal.y)return;if(state.starsCollected<state.starsTarget)return msg(`Portal blocat. Mai ai ${state.starsTarget-state.starsCollected} stele.`);if(!state.hasKey)return msg('Portal blocat. Ai nevoie de cheie.');state.score+=500+state.timeLeft*5;finish(true,`Portal activat. Bonus de timp: ${state.timeLeft*5} puncte.`)}
function useTool(name,cost){if(state.energy<cost)return msg('Energie insuficientă.');state.energy-=cost;if(name==='scan')msg('Scanner activ. Capcanele sunt vizibile.');if(name==='shield'){state.shieldCount++;msg('Scut activ.')}if(name==='magnet'){for(let i=state.stars.length-1;i>=0;i--){const s=state.stars[i];if(Math.abs(s.x-state.player.x)<=2&&Math.abs(s.y-state.player.y)<=2){state.stars.splice(i,1);state.starsCollected++;state.score+=80}}msg('Magnet activat.')}if(name==='teleport'){const a=cells(),p=a[Math.floor(Math.random()*a.length)];state.player=p;collect();trap();portal();msg('Teleportare efectuată.')}sync();draw()}
function undo(){if(!state.history.length)return msg('Nu mai există mișcări de anulat.');Object.assign(state,JSON.parse(state.history.pop()));state.moves=Math.max(0,state.moves-1);msg('Mișcare anulată.');sync();draw()}
function hint(){if(state.energy<10)return msg('Energie insuficientă.');state.energy-=10;const target=state.stars[0]||state.key||state.portal;state.hintPath=bfs(state.player,target,true);msg('Indiciu afișat.');sync();draw()}
function finish(win,text){state.running=false;state.finished=true;if(state.score>state.best){state.best=state.score;localStorage.setItem('starforge.best',state.best)}el.resultIcon.textContent=win?'★':'✕';el.resultTitle.textContent=win?'Misiune completă':'Misiune eșuată';el.resultText.textContent=text;el.resultScore.textContent=state.score;el.resultStars.textContent=`${state.starsCollected}/${state.starsTarget}`;el.resultMoves.textContent=state.moves;el.nextLevelButton.hidden=!win;el.resultOverlay.classList.remove('hidden');status(win?'Misiune completă':'Misiune eșuată',win?'':'over');sync()}
function status(t,v=''){el.statusBadge.textContent=t;el.statusBadge.className='status-badge'+(v?' '+v:'')}
function msg(t){el.messageBox.textContent=t}
function hide(){el.pauseOverlay.classList.add('hidden');el.resultOverlay.classList.add('hidden')}
function sync(){el.starsValue.textContent=state.starsCollected;el.starsTotal.textContent=state.starsTarget;el.scoreValue.textContent=state.score;el.comboValue.textContent='x'+state.combo;el.timeValue.textContent=`${String(Math.floor(state.timeLeft/60)).padStart(2,'0')}:${String(state.timeLeft%60).padStart(2,'0')}`;el.livesValue.textContent='❤'.repeat(state.lives)||'—';el.levelValue.textContent=state.level;el.bestValue.textContent=state.best;const p=state.starsTarget?Math.round(state.starsCollected/state.starsTarget*100):0;el.progressText.textContent=p+'%';el.progressBar.style.width=p+'%';el.progressTrack.setAttribute('aria-valuenow',p);el.energyValue.textContent=Math.round(state.energy)+'%';el.energyBar.style.width=state.energy+'%';el.coinValue.textContent=state.crystalCount;el.keyValue.textContent=state.keyCount;el.shieldValue.textContent=state.shieldCount;el.missionStarsText.textContent=`${state.starsCollected} din ${state.starsTarget}`;el.missionStars.classList.toggle('completed',state.starsCollected>=state.starsTarget);el.missionKeyText.textContent=state.hasKey?'Capturată':'Necapturată';el.missionKey.classList.toggle('completed',state.hasKey);const ready=state.hasKey&&state.starsCollected>=state.starsTarget;el.missionPortalText.textContent=ready?'Deblocat':'Blocat';el.missionPortal.classList.toggle('completed',ready);toolButtons.forEach(b=>b.disabled=!state.running||state.paused||state.energy<Number(b.dataset.cost));el.hintTool.disabled=!state.running||state.paused||state.energy<10;el.undoTool.disabled=!state.history.length}
function draw(){if(!state.grid.length)return;const n=state.grid.length,c=el.canvas.width/n,css=getComputedStyle(document.documentElement),col=(v,f)=>css.getPropertyValue(v).trim()||f;ctx.fillStyle=col('--bg','#080c15');ctx.fillRect(0,0,720,720);ctx.fillStyle=col('--panel2','#121a2c');state.grid.forEach((r,y)=>r.forEach((v,x)=>{if(!v)ctx.fillRect(x*c,y*c,c,c)}));if(state.hintPath.length){ctx.fillStyle='rgba(140,102,255,.28)';state.hintPath.forEach(p=>ctx.fillRect(p.x*c,p.y*c,c,c))}const glyph=(p,ch,color,s=.6)=>{ctx.fillStyle=color;ctx.font=`${Math.floor(c*s)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(ch,p.x*c+c/2,p.y*c+c/2)};glyph(state.portal,'⬡',state.hasKey&&state.starsCollected>=state.starsTarget?col('--success','#55e6a5'):col('--muted','#97a4bd'),.75);state.traps.forEach(t=>glyph(t,'×',col('--danger','#ff6178'),.7));state.stars.forEach(s=>glyph(s,'★',col('--warning','#ffcc66')));state.crystals.forEach(s=>glyph(s,'◆',col('--cyan','#3fd3ff'),.5));state.energyItems.forEach(s=>glyph(s,'✚',col('--success','#55e6a5'),.5));if(state.key)glyph(state.key,'⚿',col('--cyan','#3fd3ff'),.65);ctx.beginPath();ctx.arc(state.player.x*c+c/2,state.player.y*c+c/2,c*.32,0,Math.PI*2);ctx.fillStyle=col('--accent','#8c66ff');ctx.fill()}
function pause(force){if(!state.running||state.finished)return;state.paused=typeof force==='boolean'?force:!state.paused;el.pauseOverlay.classList.toggle('hidden',!state.paused);status(state.paused?'În pauză':'Misiune activă',state.paused?'paused':'');msg(state.paused?'Joc întrerupt.':'Joc reluat.');sync()}
document.addEventListener('keydown',e=>{if(['SELECT','INPUT'].includes(e.target.tagName)||el.helpDialog.open)return;const k=e.key.toLowerCase(),m={arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'};if(m[k]){e.preventDefault();move(m[k])}else if(k==='p')pause();else if(k==='r')build();else if(k==='u')undo();else if(k==='h')hint()});
document.querySelectorAll('.move-button').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();move(b.dataset.direction)}));toolButtons.forEach(b=>b.addEventListener('click',()=>useTool(b.dataset.tool,Number(b.dataset.cost))));el.undoTool.addEventListener('click',undo);el.hintTool.addEventListener('click',hint);el.pauseButton.addEventListener('click',()=>pause());el.resumeButton.addEventListener('click',()=>pause(false));el.restartButton.addEventListener('click',()=>build());el.playAgainButton.addEventListener('click',()=>build());el.nextLevelButton.addEventListener('click',()=>{state.level++;build(true)});el.modeSelect.addEventListener('change',()=>build());el.difficultySelect.addEventListener('change',()=>build());el.helpButton.addEventListener('click',()=>{pause(true);el.helpDialog.showModal()});el.closeHelpButton.addEventListener('click',()=>el.helpDialog.close());el.themeButton.addEventListener('click',()=>{const t=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=t;localStorage.setItem('starforge.theme',t);draw()});el.soundButton.addEventListener('click',()=>{state.soundOn=!state.soundOn;el.soundButton.textContent=state.soundOn?'🔊':'🔇';localStorage.setItem('starforge.sound',state.soundOn?'1':'0')});
setInterval(()=>{if(state.running&&!state.paused&&!state.finished){state.timeLeft--;state.energy=Math.min(100,state.energy+1);if(state.timeLeft<=0){state.timeLeft=0;finish(false,'Timpul a expirat.')}sync()}},1000);
document.documentElement.dataset.theme=localStorage.getItem('starforge.theme')||'dark';el.soundButton.textContent=state.soundOn?'🔊':'🔇';build();